version: '3.4'

services:

  packer:
    image: hashicorp/packer:1.7.10
    env_file: ./env.d/terraform
    user: ${DOCKER_USER:-1000}
    working_dir: /app
    volumes:
      - ./packer:/app
      - ./docker:/docker
      - ./env.d/docker:/env.d/docker

  terraform:
    image: hashicorp/terraform:0.15.3
    env_file: ./env.d/terraform
    user: ${DOCKER_USER:-1000}
    working_dir: /app
    volumes:
      - ./terraform:/app

  scaleway-cli:
    image: scaleway/cli
    env_file: ./env.d/terraform
    user: ${DOCKER_USER:-1000}